### ISSUE TITLE
关于档案调动

### ISSUE THREAD

**Issue by dolwin** [scscms/talent-introduction#3]
你好，我档案在老家，是不是也要去天河人才服务局开调动证明，我想了解下「同意调出函」和「档案转递接收证明」这两个东西是怎么来的。
我所在公司是注册在天河区的，由于我没有房产，所以落户的集体户是不是天河区的集体户，这个集体户的地址是怎么找，听说还要提供集体户户口页。

**Comment by scscms** [comment]
是这样的。你要确定你想把档案调入哪个人才市场（具体哪个需要自己咨询确认），我们假设为Ａ人才市场。而你的档案现在所在的人才市场我们假如为Ｂ。
首先你去找Ａ人才市场开具「档案同意接受函」，并把此函原件交给Ｂ人才市场，Ｂ人才市场会开「同意调出函」，并把你的档案和转递通知单转交给Ａ人才市场。Ａ接收到后会通知你档案到了，同时会给你提供「档案转递单」，其实就是你的档案转递回执复印件。
至于你想转哪个人才市场最好电话咨询下他们，至少要人家同意收受你，和告诉你怎么办理。

**Comment by dolwin** [comment]
被这些搞晕了，听说本科档案必须在广州才行，所以我最后还是找南方人才处理，费用 2.5k，现在等通知了

**Comment by huimiao638** [comment]
@dolwin 搞定了？我档案也是在老家，公司在白云区。

**Comment by scscms** [comment]
广东省人才市场已经开始受理2018年广东省属事业单位聘用人员和省属企业员工的人才引进，联系人：段鹏飞  联系电话：18588616106（微信同号）

**Comment by huimiao638** [comment]
我是市属的。。。 @scscms
